#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS5KPi9zdUDGgRBJt28AjGjjoUzj8E5Syqan"
APP_SECRET: "QOLA1sF6WAe15nWS1ugzo0wHF07AY2jBWHqrHWrwBx3ritDNtmD6N8wWz/bOeHekYtBUcLocYKQJiumlKuCn2kzliZFlHGKoIuF+FjPlnrZboXXjVDU6R/sWs1QoizNZF2oWi1NaUAI7ZsqPeLo2GRKTL9m3CtB0oOD2H8zTksdlJjpOW5g="

#계좌번호 앞 8자리
CANO: "68701318"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discordapp.com/api/webhooks/1058956724867973133/CnA5nMGQ9JJbNZFaSPMexxPYpZi0WrjswasopaBWo8Y99sg9b3ZCHTHbOUmb138qxjKW"